/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectrestaurantdatabase.MainFrame;

import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeString.search;
import projectrestaurantdatabase.Helper.Helper;
import projectrestaurantdatabase.Model.MenuModel;
import projectrestaurantdatabase.Model.UserModel;
import net.proteanit.sql.DbUtils;
import projectrestaurantdatabase.Controller.MenuController;
import projectrestaurantdatabase.Model.PriceModel;

/**
 *
 * @author Asus
 */
public class MenuFrame extends javax.swing.JFrame {
    
    PriceModel model1 = new PriceModel();
            
    MenuModel model = new MenuModel();
    MenuController controller = new MenuController();
    
    Helper helper = new Helper();
    String menu_database_id;
    ResultSet rs;
    
    String id_admin;
    private String total_amount;

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        initComponents();
        getAllData();
        clear();
    }
    
    public MenuFrame(UserModel userModel) {
        initComponents();
        this.clear();
        
        String labelMessage = "Hi" + total_amount;
        this.total_am.setText(labelMessage);
        
    
    }
    public void getAllData(){
        this.rs = controller.get();
        loadTable(this.rs);
    }
    public void loadTable(ResultSet rs){
        tb_menu.setModel(DbUtils.resultSetToTableModel(rs)); 
    }
        public void clear() {
        cb_ab.setSelectedIndex(0);
        cb_ig.setSelectedIndex(0);
        cb_ss.setSelectedIndex(0);
        cb_ts.setSelectedIndex(0);
        cb_et.setSelectedIndex(0);
        cb_ja.setSelectedIndex(0);
        cb_tt.setSelectedIndex(0);
        cb_mt.setSelectedIndex(0);
        tf_cash.setText("");
        
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_done.setEnabled(true);
    }
       // public void total_amount() {
        //int total_row = tb_menu.getRowCount();
        //int total_amount = 0;
        //int ayam_bakar;
        //for (int i = 0; i<total_row; i++) {  
        //ayam_bakar = Integer.parseInt(tb_menu.getValueAt(i,2).toString());
        //total_amount = total_amount + (ayam_bakar * 35000);
        //}
        //tf_tm.setText(Integer.toString(total_amount));
        //tf_tm.setText("Rp " + total_amount); 
        //}
        
       //public void loadData() {
           //DefaultTableModel Model1 = (DefaultTableModel) tb_menu.getModel1();
    //}
       
        

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_menu = new javax.swing.JTable();
        tf_cash = new javax.swing.JTextField();
        tf_search2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_search_id_order = new javax.swing.JButton();
        btn_done = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        change = new javax.swing.JLabel();
        total_am = new javax.swing.JLabel();
        cb_ab = new javax.swing.JComboBox<>();
        cb_ig = new javax.swing.JComboBox<>();
        cb_ss = new javax.swing.JComboBox<>();
        cb_ts = new javax.swing.JComboBox<>();
        cb_et = new javax.swing.JComboBox<>();
        cb_ja = new javax.swing.JComboBox<>();
        cb_tt = new javax.swing.JComboBox<>();
        cb_mt = new javax.swing.JComboBox<>();
        tf_tm = new javax.swing.JTextField();

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel7.setText("Ayam Bakar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 153));

        tb_menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_menuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_menu);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PESANAN");

        btn_search_id_order.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_search_id_order.setText("CARI DENGAN ID ORDER");
        btn_search_id_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_id_orderActionPerformed(evt);
            }
        });

        btn_done.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_done.setText("DONE");
        btn_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doneActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("AYAM BAKAR");

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("IKAN GORENG");

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SUSHI");

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TONGSENG");

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ES TEH");

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("JUS ALPUKAT");

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("THAI TEA");

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("MATCHA");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RESTAURANT MENU");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CASH");

        btn_back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_back.setText("BACK");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        change.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        change.setForeground(new java.awt.Color(255, 255, 255));
        change.setText("change");

        total_am.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        total_am.setForeground(new java.awt.Color(255, 255, 255));
        total_am.setText("total_amount");

        cb_ab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cb_ig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        cb_ss.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cb_ts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        cb_et.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        cb_ja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        cb_tt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cb_mt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_cash)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_ts, 0, 51, Short.MAX_VALUE)
                                    .addComponent(cb_ss, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_ig, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_ab, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_et, 0, 51, Short.MAX_VALUE)
                                    .addComponent(cb_ja, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_tt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_mt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_done, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_search2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btn_search_id_order)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, Short.MAX_VALUE)))
                        .addGap(52, 52, 52))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(total_am)
                                .addGap(28, 28, 28)
                                .addComponent(tf_tm, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(change))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(cb_ab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(cb_ig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cb_ja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14)
                            .addComponent(cb_ss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15)
                            .addComponent(cb_ts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_mt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_search2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_search_id_order))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_done)
                            .addComponent(btn_update))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_back)
                            .addComponent(btn_delete)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total_am)
                            .addComponent(tf_tm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(change)))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        new OrderFrame().show();
        this.dispose();
    }                                        

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {                                           
       // TODO add your handling code here:
        try {
           
            String ayam_bakar = cb_ab.getSelectedItem().toString();
            String ikan_goreng = cb_ig.getSelectedItem().toString();
            String sushi = cb_ss.getSelectedItem().toString();
            String tongseng = cb_ts.getSelectedItem().toString();
            String es_teh = cb_et.getSelectedItem().toString();
            String jus_alpukat = cb_ja.getSelectedItem().toString();
            String thai_tea = cb_tt.getSelectedItem().toString();
            String matcha = cb_mt.getSelectedItem().toString();
            String cash = tf_cash.getText();
            
            model.setAyam_bakar(ayam_bakar);
            model.setIkan_goreng(ikan_goreng);
            model.setSushi(sushi);
            model.setTongseng(tongseng);
            model.setEs_teh(es_teh);
            model.setJus_alpukat(jus_alpukat);
            model.setThai_tea(thai_tea);
            model.setMatcha(matcha);
            model.setCash(cash);

            Boolean result = controller.update(this.menu_database_id, model);
            
            String msg = "Gagal merubah data!";
            if(result) {
                msg = "Berhasil merubah data";
            }
            
            JOptionPane.showMessageDialog(null, msg);
            this.clear();
            this.getAllData();
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }                                          

    private void btn_doneActionPerformed(java.awt.event.ActionEvent evt) {                                         
      // TODO add your handling code here:
        try {
            String ayam_bakar = cb_ab.getSelectedItem().toString();
            String ikan_goreng = cb_ig.getSelectedItem().toString();
            String sushi = cb_ss.getSelectedItem().toString();
            String tongseng = cb_ts.getSelectedItem().toString();
            String es_teh = cb_et.getSelectedItem().toString();
            String jus_alpukat = cb_ja.getSelectedItem().toString();
            String thai_tea = cb_tt.getSelectedItem().toString();
            String matcha = cb_mt.getSelectedItem().toString();
            String cash = tf_cash.getText();
            

            model.setAyam_bakar(ayam_bakar);
            model.setIkan_goreng(ikan_goreng);
            model.setSushi(sushi);
            model.setTongseng(tongseng);
            model.setEs_teh(es_teh);
            model.setJus_alpukat(jus_alpukat);
            model.setThai_tea(thai_tea);
            model.setMatcha(matcha);
            model.setCash(cash);
           
            
            Boolean result = controller.create(model);
            
            String msg = "Gagal menambahkan data!";
            if(result) {
                msg = "Berhasil menambahkan data";
            }
            
            JOptionPane.showMessageDialog(null, msg);
            this.clear();
            getAllData();
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        MenuModel mm = new MenuModel();
        String ab = cb_ab.getSelectedItem().toString();
        int ayam_bakar;
        int total_amount;
        ayam_bakar = Integer.parseInt(cb_ab.getSelectedItem().toString());
        total_amount = ayam_bakar * 35000;
        DecimalFormat number = new  DecimalFormat ("###,###");
        tf_tm.setText("" + Integer.toString(total_amount));
    }                                        

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {                                           
          // TODO add your handling code here:
        try {
            
            Boolean result = controller.delete(this.menu_database_id);
            
            String msg = "Gagal menghapus data!";
            if(result) {
                msg = "Berhasil menghapus data";
            }
            
            JOptionPane.showMessageDialog(null, msg);
            
            this.clear();
            this.getAllData();
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }                                          

    private void tb_menuMouseClicked(java.awt.event.MouseEvent evt) {                                     
       // TODO add your handling code here:
     try{
         String id = helper.getValueRows(tb_menu, 0);
         String ayam_bakar = helper.getValueRows(tb_menu, 1);
         String ikan_goreng = helper.getValueRows(tb_menu, 2);
         String sushi = helper.getValueRows(tb_menu, 3);
         String tongseng = helper.getValueRows(tb_menu, 4);
         String es_teh = helper.getValueRows(tb_menu, 5);
         String jus_alpukat =  helper.getValueRows(tb_menu, 6);
         String thai_tea =  helper.getValueRows(tb_menu, 7);
         String matcha =  helper.getValueRows(tb_menu, 8);
         String cash =  helper.getValueRows(tb_menu, 9);
         
         btn_update.setEnabled(true);
         btn_delete.setEnabled(true);
         btn_done.setEnabled(true);
         
         this.menu_database_id = id;
         cb_ab.setSelectedItem(ayam_bakar);
         cb_ig.setSelectedItem(ikan_goreng);
         cb_ss.setSelectedItem(sushi);
         cb_ts.setSelectedItem(tongseng);
         cb_et.setSelectedItem(es_teh);
         cb_ja.setSelectedItem(jus_alpukat);
         cb_tt.setSelectedItem(thai_tea);
         cb_mt.setSelectedItem(matcha);
         tf_cash.setText(cash);  
     }
     catch(Exception e){
         System.out.println(e.getMessage());
     }
    }                                    

    private void btn_search_id_orderActionPerformed(java.awt.event.ActionEvent evt) {                                                    
         // TODO add your handling code here:
        search("id",tf_search2.getText());
    }                                                   
private void search(String type, String query){
        try{
            if(query.isEmpty()){
                this.rs = controller.get();
            }
            else if(type.equals("id") && !query.isEmpty()){
                this.rs = controller.showById(query);
            }
            
            loadTable(this.rs);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_done;
    private javax.swing.JButton btn_search_id_order;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cb_ab;
    private javax.swing.JComboBox<String> cb_et;
    private javax.swing.JComboBox<String> cb_ig;
    private javax.swing.JComboBox<String> cb_ja;
    private javax.swing.JComboBox<String> cb_mt;
    private javax.swing.JComboBox<String> cb_ss;
    private javax.swing.JComboBox<String> cb_ts;
    private javax.swing.JComboBox<String> cb_tt;
    private javax.swing.JLabel change;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_menu;
    private javax.swing.JTextField tf_cash;
    private javax.swing.JTextField tf_search2;
    private javax.swing.JTextField tf_tm;
    private javax.swing.JLabel total_am;
    // End of variables declaration                   
}
